import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import * as XLSX from 'xlsx';
import {createWorker} from 'tesseract.js';
import {Camera,Upload,MapPin,CheckCircle2,AlertTriangle,Download,Search,RotateCcw,Keyboard,ScanLine,Users,Cloud,CloudOff,Plus,LogOut} from 'lucide-react';
import './styles.css';

const VIN=/^[A-HJ-NPR-Z0-9]{17}$/;
const norm=s=>String(s??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const csvCell=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const cloud=!!(url&&key), supabase=cloud?createClient(url,key):null;
function distance(a,b){if(a.length!==b.length)return 99;let d=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])d++;return d}
function findHeader(headers,names){const h=headers.map(x=>String(x??'').trim().toLowerCase());for(const n of names){const i=h.findIndex(x=>x===n||x.includes(n));if(i>=0)return headers[i]}return null}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function gps(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve({});navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy}),()=>resolve({}),{enableHighAccuracy:true,timeout:10000,maximumAge:3000})})}

function App(){
 const [employee,setEmployee]=useState(localStorage.getItem('ahi_employee')||'');
 const [rows,setRows]=useState([]),[meta,setMeta]=useState(null),[session,setSession]=useState(null),[sessions,setSessions]=useState([]),[scans,setScans]=useState({}),[exceptions,setExceptions]=useState([]);
 const [tab,setTab]=useState('scan'),[msg,setMsg]=useState(null),[manual,setManual]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[ready,setReady]=useState(!cloud);
 const video=useRef(null),canvas=useRef(null),stream=useRef(null);
 const vinKey=meta?.vinKey,stockKey=meta?.stockKey, found=Object.keys(scans).length,total=rows.length;
 const byVin=useMemo(()=>new Map(rows.map(r=>[norm(r[vinKey]),r])),[rows,vinKey]);
 useEffect(()=>{if(!cloud)return; (async()=>{let {data:{session:s}}=await supabase.auth.getSession();if(!s){const x=await supabase.auth.signInAnonymously();if(x.error){setMsg({type:'bad',title:'Cloud sign-in failed',body:x.error.message});return}}setReady(true);loadSessions()})()},[]);
 useEffect(()=>()=>stopCamera(),[]);
 useEffect(()=>{if(!cloud||!session)return;const ch=supabase.channel('audit-'+session.id).on('postgres_changes',{event:'*',schema:'public',table:'inventory_scans',filter:`session_id=eq.${session.id}`},loadSessionData).on('postgres_changes',{event:'*',schema:'public',table:'inventory_exceptions',filter:`session_id=eq.${session.id}`},loadSessionData).subscribe();return()=>supabase.removeChannel(ch)},[session?.id]);
 async function loadSessions(){const {data}=await supabase.from('inventory_sessions').select('*').order('created_at',{ascending:false}).limit(20);setSessions(data||[])}
 async function loadSession(s){setBusy(true);const {data:v,error}=await supabase.from('inventory_vehicles').select('*').eq('session_id',s.id).order('stock');if(error){setBusy(false);return setMsg({type:'bad',title:'Could not load audit',body:error.message})}const reconstructed=(v||[]).map(x=>x.original_data);const headers=reconstructed[0]?Object.keys(reconstructed[0]):[];const vk=findHeader(headers,['serial','vin','vin number','vehicle identification']);const sk=findHeader(headers,['vehicle','stock','stock #','stock number']);setRows(reconstructed);setMeta({vinKey:vk,stockKey:sk,headers,file:s.source_file});setSession(s);await loadSessionData(s.id);setBusy(false)}
 async function loadSessionData(id=session?.id){if(!id)return;const [{data:a},{data:e}]=await Promise.all([supabase.from('inventory_scans').select('*').eq('session_id',id),supabase.from('inventory_exceptions').select('*').eq('session_id',id).order('scanned_at',{ascending:false})]);setScans(Object.fromEntries((a||[]).map(x=>[x.vin,x])));setExceptions(e||[])}
 async function importFile(file){
   if(!employee.trim())return setMsg({type:'warn',title:'Enter your name first',body:'Your name is attached to each vehicle you scan.'});
   setBusy(true);try{const data=await file.arrayBuffer(),wb=XLSX.read(data),ws=wb.Sheets[wb.SheetNames[0]],arr=XLSX.utils.sheet_to_json(ws,{defval:''});if(!arr.length)throw new Error('The file contains no inventory rows.');const headers=Object.keys(arr[0]),vk=findHeader(headers,['serial','vin','vin number','vehicle identification']),sk=findHeader(headers,['vehicle','stock','stock #','stock number']);if(!vk)throw new Error('VIN column not found. Expected Serial or VIN.');const clean=arr.filter(r=>VIN.test(norm(r[vk])));if(!clean.length)throw new Error('No valid 17-character VINs were found.');
   if(cloud){const name=`Physical Inventory — ${new Date().toLocaleDateString()}`;const {data:s,error}=await supabase.from('inventory_sessions').insert({name,source_file:file.name}).select().single();if(error)throw error;const payload=clean.map(r=>({session_id:s.id,vin:norm(r[vk]),stock:sk?String(r[sk]):'',description:String(r['Yr/Mk/Mdl']||''),original_data:r}));const {error:ve}=await supabase.from('inventory_vehicles').insert(payload);if(ve)throw ve;setSession(s);await loadSessions()} else setSession({id:'local',name:'Local audit',source_file:file.name});
   setRows(clean);setMeta({vinKey:vk,stockKey:sk,headers,file:file.name});setScans({});setExceptions([]);setMsg({type:'ok',title:`${clean.length} vehicles loaded`,body:'New physical inventory audit is ready.'});
   }catch(e){setMsg({type:'bad',title:'Import failed',body:e.message})}finally{setBusy(false)}
 }
 async function startCamera(){try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.current.srcObject=stream.current;await video.current.play()}catch(e){setMsg({type:'bad',title:'Camera unavailable',body:'Allow camera access, or use manual VIN entry.'})}}
 function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}
 async function saveException(v,source){const g=await gps(),rec={session_id:session?.id,vin:v,employee_name:employee.trim()||'Unknown',...g,source,scanned_at:new Date().toISOString()};if(cloud){const {error}=await supabase.from('inventory_exceptions').insert(rec);if(error)throw error;await loadSessionData()}else setExceptions(x=>[rec,...x]);setMsg({type:'warn',title:'Exception saved',body:`${v}\nNot in the loaded inventory. GPS captured when available.`})}
 async function commit(raw,source='manual'){
   if(!employee.trim())return setMsg({type:'warn',title:'Enter your name',body:'Open Setup and enter the employee scanning this inventory.'});let v=norm(raw),row=byVin.get(v),corrected=false;
   if(!row&&v.length===17){const candidates=rows.map(r=>({r,d:distance(v,norm(r[vinKey]))})).filter(x=>x.d<=1);if(candidates.length===1){row=candidates[0].r;v=norm(row[vinKey]);corrected=true}}
   if(!VIN.test(v))return setMsg({type:'bad',title:'VIN not valid',body:'VIN must contain 17 characters and cannot contain I, O or Q.'});if(scans[v])return setMsg({type:'warn',title:'Already located',body:`${scans[v].stock||v}\nScanned by ${scans[v].employee_name} at ${new Date(scans[v].scanned_at).toLocaleString()}`});
   setBusy(true);try{if(!row){await saveException(v,source);return}const g=await gps(),rec={session_id:session?.id,vin:v,stock:stockKey?String(row[stockKey]):'',employee_name:employee.trim(),...g,source,scanned_at:new Date().toISOString()};if(cloud){const vehicle=(await supabase.from('inventory_vehicles').select('id').eq('session_id',session.id).eq('vin',v).single()).data;rec.vehicle_id=vehicle?.id;const {error}=await supabase.from('inventory_scans').insert(rec);if(error){if(error.code==='23505'){await loadSessionData();setMsg({type:'warn',title:'Already located',body:'Another phone recorded this VIN first.'});return}throw error}await loadSessionData()}else setScans(s=>({...s,[v]:rec}));setManual('');setMsg({type:'ok',title:`${rec.stock||'Vehicle'} located`,body:`${row['Yr/Mk/Mdl']||''}\n${v}${corrected?'\nOCR corrected against loaded inventory.':''}${g.latitude?`\n${g.latitude.toFixed(6)}, ${g.longitude.toFixed(6)} • ±${Math.round(g.accuracy_m)} m`:'\nGPS unavailable'}`})}catch(e){setMsg({type:'bad',title:'Could not save scan',body:e.message})}finally{setBusy(false)}
 }
 async function capture(){if(!video.current?.videoWidth)return setMsg({type:'warn',title:'Start the camera first',body:'Then align the printed VIN inside the frame.'});setBusy(true);const v=video.current,c=canvas.current;c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);try{const worker=await createWorker('eng');await worker.setParameters({tessedit_char_whitelist:'ABCDEFGHJKLMNPRSTUVWXYZ0123456789'});const {data}=await worker.recognize(c);await worker.terminate();const compact=norm(data.text),tokens=[...(data.text.toUpperCase().match(/[A-Z0-9]{10,20}/g)||[]).map(norm)];for(let i=0;i<=compact.length-17;i++)tokens.push(compact.slice(i,i+17));let exact=tokens.find(x=>VIN.test(x)&&byVin.has(x));if(exact)await commit(exact,'ocr');else{let best=null;for(const t of tokens.filter(x=>x.length===17&&VIN.test(x)))for(const [known] of byVin){const d=distance(t,known);if(!best||d<best.d)best={known,d}}if(best&&best.d<=1)await commit(best.known,'ocr');else setMsg({type:'warn',title:'VIN not confidently read',body:'Move closer or change the windshield angle, then scan again. Manual entry is always available.'})}}catch(e){setMsg({type:'bad',title:'OCR failed',body:'Try again or use manual VIN entry.'})}finally{setBusy(false)}}
 function exportCSV(){const headers=[...meta.headers,'Physical Inventory Status','Scan Timestamp','Scanned By','Latitude','Longitude','GPS Accuracy (m)'];const lines=[headers.map(csvCell).join(',')];for(const r of rows){const s=scans[norm(r[vinKey])],vals=meta.headers.map(h=>r[h]);vals.push(s?'FOUND':'NOT FOUND',s?.scanned_at||'',s?.employee_name||'',s?.latitude??'',s?.longitude??'',s?.accuracy_m??'');lines.push(vals.map(csvCell).join(','))}download('Audi-Hampton-Physical-Inventory.csv',lines.join('\r\n'),'text/csv')}
 function exportKML(){const pts=Object.values(scans).filter(s=>s.latitude!=null);const body=pts.map(s=>{const r=byVin.get(s.vin)||{};return `<Placemark><name>${esc(s.stock||s.vin)}</name><description>${esc((r['Yr/Mk/Mdl']||'')+' | '+s.vin+' | '+s.employee_name+' | '+new Date(s.scanned_at).toLocaleString())}</description><Point><coordinates>${s.longitude},${s.latitude},0</coordinates></Point></Placemark>`}).join('');download('Audi-Hampton-Vehicle-Locations.kml',`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Audi Hampton Vehicle Locations</name>${body}</Document></kml>`,'application/vnd.google-earth.kml+xml')}
 const filtered=rows.filter(r=>!query||Object.values(r).some(x=>String(x).toLowerCase().includes(query.toLowerCase()))),scannerCounts=Object.values(scans).reduce((a,s)=>(a[s.employee_name]=(a[s.employee_name]||0)+1,a),{});
 if(!ready)return <div className="splash">Connecting inventory…</div>;
 if(!session)return <div className="app"><header><div className="rings">○○○○</div><div><b>AUDI HAMPTON</b><span>PHYSICAL INVENTORY</span></div></header><main className="empty"><Cloud size={42}/><h1>Start or join an audit</h1><div className="namebox"><label>Your name</label><input value={employee} placeholder="Employee name" onChange={e=>{setEmployee(e.target.value);localStorage.setItem('ahi_employee',e.target.value)}}/></div><label className="primary"><Plus/> Start new audit from XLSX/CSV<input type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>e.target.files[0]&&importFile(e.target.files[0])}/></label>{cloud&&sessions.length>0&&<div className="sessions"><b>Recent shared audits</b>{sessions.map(s=><button key={s.id} onClick={()=>loadSession(s)}><span>{s.name}</span><small>{s.source_file} • {new Date(s.created_at).toLocaleString()}</small></button>)}</div>}<small>{cloud?'Cloud sync enabled • multiple phones can join the same audit':'Local-only mode • add Supabase settings for multi-phone sync'}</small></main></div>;
 return <div className="app"><header><div className="rings">○○○○</div><div><b>AUDI HAMPTON</b><span>PHYSICAL INVENTORY</span></div><button className="headbtn" onClick={()=>{stopCamera();setSession(null);setRows([]);setScans({})}}><LogOut/></button></header><div className="sync">{cloud?<><Cloud/> LIVE SHARED AUDIT</>:<><CloudOff/> LOCAL MODE</>}<span>{employee||'No employee name'}</span></div><div className="progress"><strong>{found} / {total}</strong><span>VEHICLES LOCATED</span><div><i style={{width:`${total?found/total*100:0}%`}}/></div></div><nav><button className={tab==='scan'?'active':''} onClick={()=>setTab('scan')}><ScanLine/>Scan</button><button className={tab==='inventory'?'active':''} onClick={()=>setTab('inventory')}><Search/>Inventory</button><button className={tab==='team'?'active':''} onClick={()=>setTab('team')}><Users/>Team</button><button className={tab==='export'?'active':''} onClick={()=>setTab('export')}><Download/>Export</button></nav><main>
 {tab==='scan'&&<section><div className="camera"><video ref={video} playsInline muted/><canvas ref={canvas} hidden/><div className="guide"><span>ALIGN PRINTED VIN INSIDE FRAME</span></div></div><div className="actions"><button onClick={startCamera}><Camera/>Start camera</button><button className="primary" disabled={busy} onClick={capture}><ScanLine/>{busy?'Reading…':'Read VIN'}</button></div><div className="manual"><Keyboard/><input value={manual} maxLength={17} placeholder="Or enter 17-character VIN" onChange={e=>setManual(e.target.value.toUpperCase())}/><button disabled={busy} onClick={()=>commit(manual)}>Confirm</button></div><p className="note">Printed VIN OCR is primary. A barcode is not required. Location is captured only when the browser grants GPS permission.</p></section>}
 {tab==='inventory'&&<section><div className="search"><Search/><input placeholder="Stock, VIN, model…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="list">{filtered.map((r,i)=>{const v=norm(r[vinKey]),s=scans[v];return <div className="vehicle" key={v}><div className={s?'dot found':'dot'}>{s?<CheckCircle2/>:<span>{i+1}</span>}</div><div><b>{stockKey?r[stockKey]:v}</b><span>{r['Yr/Mk/Mdl']||''}</span><small>{v}</small>{s&&<small>{s.employee_name} • {new Date(s.scanned_at).toLocaleTimeString()}</small>}{s?.latitude!=null&&<small><MapPin/> {s.latitude.toFixed(6)}, {s.longitude.toFixed(6)} ±{Math.round(s.accuracy_m)}m</small>}</div></div>})}</div></section>}
 {tab==='team'&&<section className="export"><h2>Shared audit</h2><div className="stats"><div><b>{Object.keys(scannerCounts).length}</b><span>Scanners</span></div><div><b>{found}</b><span>Located</span></div><div><b>{exceptions.length}</b><span>Exceptions</span></div></div>{Object.entries(scannerCounts).map(([n,c])=><div className="teamrow" key={n}><b>{n}</b><span>{c} scanned</span></div>)}{exceptions.length>0&&<><h3>VINs not in inventory</h3>{exceptions.map(e=><div className="teamrow" key={e.id||e.scanned_at}><div><b>{e.vin}</b><small>{e.employee_name}</small></div><span>{e.latitude!=null?`${e.latitude.toFixed(6)}, ${e.longitude.toFixed(6)}`:'No GPS'}</span></div>)}</>}</section>}
 {tab==='export'&&<section className="export"><h2>Reconciliation</h2><div className="stats"><div><b>{total}</b><span>Expected</span></div><div><b>{found}</b><span>Located</span></div><div><b>{total-found}</b><span>Missing</span></div></div><button className="primary" onClick={exportCSV}><Download/>Export reconciled CSV</button><button onClick={exportKML}><MapPin/>Export Google Earth KML</button><p className="note">CSV preserves every original inventory column and appends status, timestamp, scanner, latitude, longitude and GPS accuracy.</p></section>}</main>
 {msg&&<div className={'toast '+msg.type} onClick={()=>setMsg(null)}>{msg.type==='ok'?<CheckCircle2/>:<AlertTriangle/>}<div><b>{msg.title}</b><span>{msg.body}</span></div></div>}<footer><span>{meta?.file}</span><span>{session.name}</span></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
